"""LLM writer for in-scene suggested action chips (SC1-C).

The chips answer "我現在可以做什麼" for a player who opened a scene
precisely because they did not want to think of an opening move. They are
generated by a model reading the live scene frame plus the last few
turns — never assembled from a phrase table, never branched on
``scene_type`` (red line 5).

**Fail-soft by construction.** Unlike the opener — whose failure fails a
paid action — a missing chip costs the player nothing: the input box is
right there and the scene plays identically. So every failure mode here
(no model, fake model, upstream error, unparseable output, empty list)
converges on the same answer: an empty tuple. Nothing above this seam has
to distinguish them, which is why neither implementation raises.
"""

from __future__ import annotations

import asyncio
import logging
import re

from kokoro_link.application.services.model_resolver import ModelResolver
from kokoro_link.contracts.active_llm import ActiveLLMProviderPort
from kokoro_link.contracts.llm import ChatModelPort
from kokoro_link.contracts.story_scene import (
    StorySceneChipsContext,
    StorySceneChipsWriterPort,
)
from kokoro_link.infrastructure.prompt.operator_language import (
    render_operator_language_hint,
)
from kokoro_link.infrastructure.prompts import get_default_loader
from kokoro_link.llm_output import extract_object_outcome, log_parse_outcome


_LOGGER = logging.getLogger(__name__)

_MAX_CHIP_CHARS = 80
"""A chip is a tap target, not a paragraph.

Counted in characters, so the same limit has to hold a ~15-character
zh-TW line and the ~50-character en rendering of the same idea — sized
for the looser of the two rather than the tighter, because a cap that
only zh-TW clears would mean en/ja players silently never see chips.
Over-length candidates are dropped rather than truncated: half a sentence
offered as a suggested move is worse than one chip fewer."""

_MIN_CHIPS = 2
_MAX_CHIPS = 3

_TIMEOUT_SECONDS = 30.0
"""Hard bound on the call, because of *where* it runs.

Both callers hold the conversation's turn lease while waiting for chips —
the opening holds it, and the streaming finalizer holds it until the
``done`` frame goes out. An upstream that accepts the request and then
never answers would therefore lock the player's own conversation until
the lease TTL expires, over a suggestion they never needed. Generous
enough for a slow local model, far below the 180s lease."""

_UNSPECIFIED = "（未指定）"


class NullStorySceneChipsWriter(StorySceneChipsWriterPort):
    """Null object for wiring without an LLM: no chips, ever.

    A real implementation rather than ``None`` so callers depend on the
    port unconditionally and the "no chips" path is the *same* path in
    every deployment instead of an extra branch that only self-host
    without a model ever takes.
    """

    async def suggest_actions(
        self, context: StorySceneChipsContext,
    ) -> tuple[str, ...]:
        return ()


class LLMStorySceneChipsWriter(StorySceneChipsWriterPort):
    def __init__(
        self,
        *,
        model: ChatModelPort | None = None,
        provider: ActiveLLMProviderPort | None = None,
        feature_key: str | None = None,
    ) -> None:
        self._resolver = ModelResolver(
            provider=provider,
            model=model,
            feature_key=feature_key,
        )

    async def suggest_actions(
        self, context: StorySceneChipsContext,
    ) -> tuple[str, ...]:
        # The fake backend emits deterministic junk; offering it as a
        # suggested player move would put obvious filler on the stage.
        try:
            if await self._resolver.is_fake(character=context.character):
                return ()
            raw = await asyncio.wait_for(
                self._resolver.generate(
                    _build_prompt(context),
                    character=context.character,
                ),
                timeout=_TIMEOUT_SECONDS,
            )
        except Exception:
            _LOGGER.info(
                "story scene chips unavailable character=%s scene=%s",
                context.character.id,
                context.session.id,
                exc_info=True,
            )
            return ()
        return _parse_actions(raw, limit=_chip_limit(context.max_chips))


def _chip_limit(requested: int) -> int:
    return max(_MIN_CHIPS, min(_MAX_CHIPS, int(requested or _MAX_CHIPS)))


def _build_prompt(context: StorySceneChipsContext) -> str:
    session = context.session
    language_hint = render_operator_language_hint(
        context.operator_primary_language,
    )
    body = get_default_loader().render(
        "story/scene_chips",
        character_name=context.character.name,
        character_summary=context.character.summary or _UNSPECIFIED,
        speaking_style=context.character.speaking_style or "自然",
        scene_title=session.title or _UNSPECIFIED,
        scene_location=session.location or _UNSPECIFIED,
        scene_mood=session.mood or _UNSPECIFIED,
        scene_type=session.scene_type or _UNSPECIFIED,
        dramatic_question=session.dramatic_question or _UNSPECIFIED,
        recent_lines=(
            "\n".join(context.recent_lines)
            if context.recent_lines
            else "（這場戲剛拉開序幕，還沒有對話）"
        ),
        max_chips=_chip_limit(context.max_chips),
    )
    return f"{language_hint}\n\n{body}" if language_hint else body


def _parse_actions(raw: str, *, limit: int) -> tuple[str, ...]:
    outcome = extract_object_outcome(raw, repair_truncated=True)
    log_parse_outcome(_LOGGER, outcome, site="story.scene_chips")
    parsed = outcome.value
    if parsed is None:
        return ()
    actions = parsed.get("actions")
    if not isinstance(actions, list):
        return ()
    cleaned: list[str] = []
    seen: set[str] = set()
    for candidate in actions:
        text = _clean(candidate)
        if not text:
            continue
        # Exact repeats are the model failing the "彼此要不一樣"
        # instruction; showing the same chip twice reads as a bug.
        key = text.casefold()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(text)
        if len(cleaned) == limit:
            break
    # One chip is not a choice — it reads as the game telling the player
    # what to do. Below the floor we offer none and let them type.
    if len(cleaned) < _MIN_CHIPS:
        return ()
    return tuple(cleaned)


def _clean(value: object) -> str:
    if not isinstance(value, str):
        return ""
    text = re.sub(r"\s+", " ", value.strip())
    # Models like to number their suggestions and wrap them in quotes;
    # strip the decoration so the chip lands in the composer as plain
    # input text. Numbering comes off first — it sits *outside* the
    # quotes ("1. 「…」"), so stripping quotes first would find a digit.
    text = re.sub(r"^[0-9]+\s*[.、)]\s*", "", text)
    text = text.strip("「」『』\"'“”·-—　 ")
    if len(text) > _MAX_CHIP_CHARS:
        return ""
    return text
