"""``.lumebackup`` DTO contract (CB0) — schema version, manifest,
per-table row DTOs, and the character-data boundary registry.

Split by data domain to keep each module small; import from this package
rather than the submodules. See ``registry.py`` for the authoritative
table → classification → DTO map and ``base.py`` for the row/DTO value
conventions.
"""

from kokoro_link.application.dto.character_backup.base import BackupRecord
from kokoro_link.application.dto.character_backup.character import (
    CharacterBackupRecord,
)
from kokoro_link.application.dto.character_backup.consumer_policies import (
    BACKUP_CLASSIFICATION_DEFAULTS,
    BACKUP_TABLE_OVERRIDES,
    DELETE_CLASSIFICATION_DEFAULTS,
    DELETE_TABLE_OVERRIDES,
    LUMECARD_SCOPE,
    RESET_FLAG_EFFECTS,
    RESET_UNTOUCHED_REASON,
    SURVIVING_POLICIES,
    TABLE_POLICY_CONSUMERS,
    ClassificationDefault,
    DataConsumer,
    DeletePolicy,
    LumecardScope,
    PolicyOverride,
    PolicySource,
    ResetFlag,
    ResetPolicy,
    ResetTableEffect,
    ResolvedPolicy,
    UnresolvedPolicyError,
    lumecard_excluded_columns,
    policy_for,
    reset_effects_for_flag,
    reset_primary_table_for_flag,
    reset_tables_for_flag,
)
from kokoro_link.application.dto.character_backup.conversation import (
    ConversationBackupRecord,
    DeferredIntentBackupRecord,
    MessageBackupRecord,
    PendingFollowUpBackupRecord,
    TurnJournalBackupRecord,
)
from kokoro_link.application.dto.character_backup.feed import (
    CharacterAlbumItemBackupRecord,
    FeedCommentBackupRecord,
    FeedPostBackupRecord,
    FeedReactionBackupRecord,
)
from kokoro_link.application.dto.character_backup.manifest import (
    BACKUP_SCHEMA_VERSION,
    BackupExportReport,
    BackupMediaEntry,
    BackupNsfwCollapseStats,
    CharacterBackupManifest,
)
from kokoro_link.application.dto.character_backup.memory import (
    MemoirPinBackupRecord,
    MemoryItemBackupRecord,
)
from kokoro_link.application.dto.character_backup.persona import (
    CharacterOperatorRelationshipSeedBackupRecord,
    OperatorAddressChangeLogBackupRecord,
    OperatorAddressPreferenceBackupRecord,
    OperatorProfileFieldBackupRecord,
    PersonaCuriosityAttemptBackupRecord,
    PlayerPersonaNoteBackupRecord,
)
from kokoro_link.application.dto.character_backup.registry import (
    BACKUP_TABLE_RULES_BY_NAME,
    BackupClassification,
    BackupTableRule,
    CHARACTER_BACKUP_TABLE_RULES,
    CHARACTER_MEDIA_URL_FIELDS,
    CHARACTER_STORAGE_PREFIXES,
    CharacterStoragePrefix,
    ExcludedColumn,
    MediaUrlField,
    MediaUrlShape,
    OPERATOR_SCOPED_MEDIA_PREFIXES,
    carried_table_rules,
    character_storage_prefixes,
    media_url_fields_by_table,
    operator_scoped_media_prefixes,
)
from kokoro_link.application.dto.character_backup.schedule import (
    DailyScheduleBackupRecord,
    ScheduleActivityBackupRecord,
)
from kokoro_link.application.dto.character_backup.state_profile import (
    BehavioralPatternBackupRecord,
    CharacterGoalBackupRecord,
    DispositionDriftHistoryBackupRecord,
    EmotionEventBackupRecord,
    SelfReflectionBackupRecord,
    StateSnapshotBackupRecord,
)
from kokoro_link.application.dto.character_backup.story import (
    CharacterSeriesProgressBackupRecord,
    StoryArcBackupRecord,
    StoryArcBeatBackupRecord,
    StoryEventBackupRecord,
    StorySceneSessionBackupRecord,
    StorySeedBackupRecord,
)

__all__ = [
    "BACKUP_CLASSIFICATION_DEFAULTS",
    "BACKUP_SCHEMA_VERSION",
    "BACKUP_TABLE_OVERRIDES",
    "BACKUP_TABLE_RULES_BY_NAME",
    "CHARACTER_BACKUP_TABLE_RULES",
    "CHARACTER_MEDIA_URL_FIELDS",
    "CHARACTER_STORAGE_PREFIXES",
    "DELETE_CLASSIFICATION_DEFAULTS",
    "DELETE_TABLE_OVERRIDES",
    "LUMECARD_SCOPE",
    "OPERATOR_SCOPED_MEDIA_PREFIXES",
    "RESET_FLAG_EFFECTS",
    "RESET_UNTOUCHED_REASON",
    "SURVIVING_POLICIES",
    "TABLE_POLICY_CONSUMERS",
    "BackupClassification",
    "BackupExportReport",
    "BackupMediaEntry",
    "BackupNsfwCollapseStats",
    "BackupRecord",
    "BackupTableRule",
    "BehavioralPatternBackupRecord",
    "CharacterAlbumItemBackupRecord",
    "CharacterBackupManifest",
    "CharacterBackupRecord",
    "CharacterGoalBackupRecord",
    "CharacterOperatorRelationshipSeedBackupRecord",
    "CharacterSeriesProgressBackupRecord",
    "CharacterStoragePrefix",
    "ClassificationDefault",
    "ConversationBackupRecord",
    "DataConsumer",
    "DeletePolicy",
    "DailyScheduleBackupRecord",
    "DeferredIntentBackupRecord",
    "DispositionDriftHistoryBackupRecord",
    "EmotionEventBackupRecord",
    "ExcludedColumn",
    "FeedCommentBackupRecord",
    "FeedPostBackupRecord",
    "FeedReactionBackupRecord",
    "LumecardScope",
    "MediaUrlField",
    "MediaUrlShape",
    "MemoirPinBackupRecord",
    "MemoryItemBackupRecord",
    "MessageBackupRecord",
    "OperatorAddressChangeLogBackupRecord",
    "OperatorAddressPreferenceBackupRecord",
    "OperatorProfileFieldBackupRecord",
    "PendingFollowUpBackupRecord",
    "PersonaCuriosityAttemptBackupRecord",
    "PlayerPersonaNoteBackupRecord",
    "PolicyOverride",
    "PolicySource",
    "ResetFlag",
    "ResetPolicy",
    "ResetTableEffect",
    "ResolvedPolicy",
    "ScheduleActivityBackupRecord",
    "SelfReflectionBackupRecord",
    "StateSnapshotBackupRecord",
    "StoryArcBackupRecord",
    "StoryArcBeatBackupRecord",
    "StoryEventBackupRecord",
    "StorySceneSessionBackupRecord",
    "StorySeedBackupRecord",
    "TurnJournalBackupRecord",
    "UnresolvedPolicyError",
    "carried_table_rules",
    "character_storage_prefixes",
    "lumecard_excluded_columns",
    "media_url_fields_by_table",
    "operator_scoped_media_prefixes",
    "policy_for",
    "reset_effects_for_flag",
    "reset_primary_table_for_flag",
    "reset_tables_for_flag",
]
