"""PendingFollowUp — deferred-reply record.

When the character is too busy (high ``busy_score`` activity in progress)
to write a full reply, ``ChatService`` takes a two-step path:

1. Inline turn: a short, in-character "I'm busy — I'll get back to you"
   acknowledgement is generated by the LLM and persisted as the
   assistant message of this turn so the user gets immediate feedback.
2. Pending follow-up: this entity records the user message(s) that
   still need a proper answer. The proactive scheduler later notices the
   character is no longer busy and asks the LLM to write the actual
   reply, which is then fanned out via the existing proactive-message
   pipeline (web SSE + Telegram/LINE bindings).

Concurrency policy — **single defer, then reply**:
  If the user keeps typing while a follow-up is pending, every new
  user message is appended to the row for audit, then ChatService
  cancels the row and lets the normal chat path answer immediately.
  This prevents the worst IM experience: a brief "I'll reply later"
  followed by silent swallowed messages. ``MAX_QUEUED_MESSAGES`` remains
  for legacy rows and dispatcher force-release protection.

Lifecycle:
  ``queued`` → (tick sees busy_score drop) → ``resolving`` → success
  → ``resolved`` (terminal). Failure during resolve flips back to
  ``queued`` so the next tick retries.

  One kind of failure does not simply flip back: a compose the HV1
  honesty gate withheld (:meth:`PendingFollowUp.honesty_parked` /
  :meth:`PendingFollowUp.honesty_retries_exhausted`). An unbounded,
  un-delayed retry there is a model that keeps lying being asked to lie
  again every tick, forever, from the head of the due queue — so the
  release instant moves forward, and a model that re-offends through its
  whole budget ends the row instead of owning it silently.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from datetime import datetime, timezone
from hashlib import sha256
from typing import ClassVar
from unicodedata import normalize
from uuid import uuid4
from kokoro_link.domain.value_objects.commitment import normalize_commitment_key

from kokoro_link.domain.entities.conversation import MessageContentMode


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


MAX_QUEUED_MESSAGES: int = 8
"""How many user messages can be merged into a single pending row before
the dispatcher force-releases it on the next tick regardless of the
character's current ``busy_score``. Picked so the eventual follow-up
prompt fits comfortably within a single LLM call."""

_SCHEDULED_PROMISE_SLOT_MINUTES = 15
"""Width of one scheduled-promise delivery window.

Post-turn extraction can phrase one appointment in several slightly different
ways.  Keeping all obligations in one short delivery window produces one
natural callback instead of several near-identical notifications.
"""


def scheduled_promise_dedupe_key(
    *,
    character_id: str,
    promise_intent: str,
    scheduled_for: datetime,
) -> str:
    """Return the stable identity for one open scheduled promise.

    Promise extraction can be retried by the post-turn worker, so the random
    row UUID is unsuitable for deduplication.  The promise is instead keyed by
    its character, normalized action, and UTC minute.  Source conversation is
    deliberately excluded: a player should not receive the same promised
    action twice merely because the extractor saw mirrored conversation data.
    """
    if scheduled_for.tzinfo is None:
        raise ValueError("scheduled_for must be tz-aware")
    normalized_intent = " ".join(
        normalize("NFKC", promise_intent).casefold().split(),
    )
    scheduled_minute = scheduled_for.astimezone(timezone.utc).replace(
        second=0, microsecond=0,
    )
    payload = "\x1f".join((
        character_id.strip(),
        PendingFollowUpKind.SCHEDULED_PROMISE.value,
        normalized_intent,
        scheduled_minute.isoformat(),
    ))
    return sha256(payload.encode("utf-8")).hexdigest()


def scheduled_promise_delivery_slot_key(
    *,
    character_id: str,
    scheduled_for: datetime,
) -> str:
    """Return the stable identity for one character delivery window.

    A character has one player in the self-host model, so the character id
    represents the player side of the appointment as well.  We intentionally
    do not include ``conversation_id``: mirrored web/channel conversation
    records must still collapse into one visible callback.
    """
    if scheduled_for.tzinfo is None:
        raise ValueError("scheduled_for must be tz-aware")
    scheduled_utc = scheduled_for.astimezone(timezone.utc)
    slot_start = scheduled_utc.replace(
        minute=(scheduled_utc.minute // _SCHEDULED_PROMISE_SLOT_MINUTES)
        * _SCHEDULED_PROMISE_SLOT_MINUTES,
        second=0,
        microsecond=0,
    )
    payload = "\x1f".join((
        character_id.strip(),
        PendingFollowUpKind.SCHEDULED_PROMISE.value,
        slot_start.isoformat(),
    ))
    return sha256(payload.encode("utf-8")).hexdigest()


def scheduled_promise_source_turn_key(
    *,
    source_text: str,
) -> str:
    """Give one extracted source turn a repeat-stable identity.

    The post-turn result does not currently expose a durable source-message id
    on every channel.  A normalized source-text fingerprint is therefore the
    best portable key; it is used only inside one delivery window and never
    shown to the player.
    """
    normalized_source = " ".join(
        normalize("NFKC", source_text).casefold().split(),
    )
    return sha256(normalized_source.encode("utf-8")).hexdigest()


@dataclass(frozen=True, slots=True)
class PendingFollowUpMessage:
    """One queued user message waiting for the deferred reply."""

    content: str
    queued_at: datetime
    content_mode: MessageContentMode = MessageContentMode.NORMAL
    safe_summary: str = ""
    message_id: str | None = None
    """Id of the corresponding ``MessageRow`` (web conversation), when
    available. Optional because TG/LINE inbound messages may not have a
    stable id yet at queue time."""

    @classmethod
    def new(
        cls,
        *,
        content: str,
        queued_at: datetime | None = None,
        content_mode: MessageContentMode | str = MessageContentMode.NORMAL,
        safe_summary: str = "",
        message_id: str | None = None,
    ) -> "PendingFollowUpMessage":
        text = content.strip()
        if not text:
            raise ValueError("PendingFollowUpMessage content must be non-empty")
        return cls(
            content=text,
            queued_at=queued_at or _utcnow(),
            content_mode=_coerce_content_mode(content_mode),
            safe_summary=(safe_summary or "").strip(),
            message_id=message_id,
        )


@dataclass(frozen=True, slots=True)
class ScheduledPromiseObligation:
    """One promise that shares a visible scheduled delivery.

    ``PendingFollowUp`` remains the lifecycle record.  This value keeps the
    individual things the character promised, so duplicate extraction produces
    one callback without silently discarding a distinct obligation.
    """

    intent: str
    source_turn_key: str
    source_text: str = ""

    def __post_init__(self) -> None:
        cleaned_intent = (self.intent or "").strip()
        if not cleaned_intent:
            raise ValueError("ScheduledPromiseObligation.intent must be non-empty")
        object.__setattr__(self, "intent", cleaned_intent[:500])
        object.__setattr__(self, "source_turn_key", (self.source_turn_key or "").strip())
        object.__setattr__(self, "source_text", (self.source_text or "").strip()[:500])

    @property
    def identity(self) -> tuple[str, str]:
        """Identity used when a post-turn retry re-submits the same promise."""
        normalized_intent = " ".join(
            normalize("NFKC", self.intent).casefold().split(),
        )
        return self.source_turn_key, normalized_intent


def _coerce_content_mode(value: MessageContentMode | str) -> MessageContentMode:
    if isinstance(value, MessageContentMode):
        return value
    try:
        return MessageContentMode(str(value).strip().lower())
    except ValueError:
        return MessageContentMode.NORMAL


@dataclass(frozen=True, slots=True)
class PendingFollowUpStatus:
    """String-valued VO so new statuses can be added without alembic."""

    value: str

    QUEUED: ClassVar["PendingFollowUpStatus"]
    RESOLVING: ClassVar["PendingFollowUpStatus"]
    RESOLVED: ClassVar["PendingFollowUpStatus"]
    CANCELLED: ClassVar["PendingFollowUpStatus"]

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("PendingFollowUpStatus value must be non-empty")
        object.__setattr__(self, "value", self.value.strip().lower())

    def __str__(self) -> str:
        return self.value


PendingFollowUpStatus.QUEUED = PendingFollowUpStatus("queued")
PendingFollowUpStatus.RESOLVING = PendingFollowUpStatus("resolving")
PendingFollowUpStatus.RESOLVED = PendingFollowUpStatus("resolved")
PendingFollowUpStatus.CANCELLED = PendingFollowUpStatus("cancelled")


@dataclass(frozen=True, slots=True)
class PendingFollowUpKind:
    """Discriminator for the two reasons a pending follow-up exists.

    * ``BUSY_DEFER`` — the original use case. The user wrote during a
      high-busy activity; the character gave a brief ack inline; the
      full reply is owed when the character is free.
    * ``SCHEDULED_PROMISE`` — the user explicitly asked the character
      to message them at a future time ("明天 10 點叫我起床"). No
      brief ack was given; the message is generated fresh at the
      promised time.

    Kept as a VO (not Enum) so adding new kinds (e.g. ``REMINDER``)
    doesn't require an alembic migration on the column type.
    """

    value: str

    BUSY_DEFER: ClassVar["PendingFollowUpKind"]
    SCHEDULED_PROMISE: ClassVar["PendingFollowUpKind"]

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("PendingFollowUpKind value must be non-empty")
        object.__setattr__(self, "value", self.value.strip().lower())

    def __str__(self) -> str:
        return self.value


PendingFollowUpKind.BUSY_DEFER = PendingFollowUpKind("busy_defer")
PendingFollowUpKind.SCHEDULED_PROMISE = PendingFollowUpKind("scheduled_promise")

SCHEDULED_PROMISE_DEFER_REASON: str = "scheduled_promise"
"""``defer_reason`` of a promise the *character* made to the player."""

HONESTY_REPAIR_DEFER_REASON: str = "honesty_repair"
"""``defer_reason`` of a row the HV4 chat audit minted for itself (F5).

A repair row is a ``SCHEDULED_PROMISE`` in every way that matters
downstream — same composer, same release job, same honesty gate on the
re-compose — so it deliberately does **not** get a ``kind`` of its own;
a third kind would have to be taught to every ``kind ==
SCHEDULED_PROMISE`` branch in the dispatcher and would be wrong in all
of them.

What it does need is to be **recognisable to its own writer**, because
that writer has to find the row it wrote two minutes ago and merge the
next caught lie into it rather than opening a second one (F5). This
constant is that recognition: a discriminator the machine stamps at mint
time, checked by equality. It is emphatically *not* a reading of the
row's prose — matching on what ``promise_intent`` says would be exactly
the keyword special-casing the project's first principle forbids, and
would also break the moment the composer's wording changed.

Collision-free by construction: ``defer_reason`` is otherwise either the
busy-decider's free-text label (only ever on ``BUSY_DEFER`` rows, which
this predicate excludes) or the fixed
:data:`SCHEDULED_PROMISE_DEFER_REASON`.
"""


@dataclass(frozen=True, slots=True)
class PendingFollowUp:
    """A promise to the user that an actual reply is coming once the
    character finishes what they're busy with.

    Attribute reference:

    * ``brief_reply`` — the in-character short acknowledgement the user
      already saw inline ("先回會議結束我再好好回你"). The deferred-
      reply LLM call sees this so the eventual full reply can honour
      the promise instead of contradicting it.
    * ``defer_reason`` — short label from the busy-decider ("會議中" /
      "通勤" / "深度工作") for telemetry + prompt context. Not
      enumerated; whatever the LLM wrote stays.
    * ``scheduled_for`` — earliest time the dispatcher should consider
      releasing this row. The dispatcher additionally checks the
      character's current busy_score; both gates must pass.
    * ``messages`` — tuple of queued user messages (FIFO order). New
      messages append via :meth:`appended`. Cap enforced at the service
      layer, not the entity, so the dispatcher can choose to force-
      release at-cap rather than rejecting the append (UX: never silently
      drop the user's words).
    """

    id: str
    character_id: str
    conversation_id: str
    status: PendingFollowUpStatus
    messages: tuple[PendingFollowUpMessage, ...]
    brief_reply: str
    defer_reason: str
    activity_id: str | None
    """``ScheduleActivity.id`` the decider was looking at when it
    deferred. Optional because the user might message during a schedule
    gap where ``busy_score`` is high for a non-schedule reason (e.g.
    energy heuristic). Used for telemetry / debugging only — the
    dispatcher re-resolves the current activity at release time."""
    scheduled_for: datetime
    queued_at: datetime
    updated_at: datetime
    resolved_at: datetime | None = None
    resolved_message: str | None = None
    """The full deferred-reply text once successfully delivered. Kept
    for audit / debugging — the eventual outbound is also written into
    the conversation history through the normal fan-out path."""
    last_error: str | None = None
    kind: PendingFollowUpKind = field(
        default_factory=lambda: PendingFollowUpKind.BUSY_DEFER,
    )
    """Why this row exists. ``BUSY_DEFER`` (default) keeps every legacy
    code path identical; ``SCHEDULED_PROMISE`` routes the dispatcher to
    the scheduled-promise composer and skips the busy-score release
    gate (the original promise didn't promise "when I'm free", it
    promised "at this specific time")."""
    promise_intent: str = ""
    """The natural-language description of what the character promised
    to do at the scheduled time (例:「叫使用者起床」「提醒喝水」).
    Only meaningful when ``kind == SCHEDULED_PROMISE``; ignored for
    ``BUSY_DEFER``. The composer reads this to write the actual message
    — the persona + intent + current context drive content, no
    templating."""
    dedupe_key: str = ""
    delivery_slot_key: str = ""
    source_turn_key: str = ""
    obligations: tuple[ScheduledPromiseObligation, ...] = ()
    commitment_key: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "commitment_key", normalize_commitment_key(self.commitment_key),
        )
    turn_record_id: str | None = None
    """Id of the ``turn_records`` row for the turn that wrote this — the
    anchor turn-undo deletes by (TU4).

    Only a ``SCHEDULED_PROMISE`` row carries one, because only that row
    is written by the background post-turn, whose clock has nothing to do
    with the turn's. Undoing a *later* turn used to hard-delete such a
    row purely because it landed inside that turn's time window, killing
    a promise the character made in a message still on screen.

    ``None`` on a ``BUSY_DEFER`` row is permanent and correct: that
    branch runs no post-turn and mints no turn record, and its row is
    written inline during the turn, which is the one case the window is
    exact for. ``None`` on a promise row also covers rows written before
    the anchor existed — every reader must treat it as "no anchor
    available", never as an error."""
    honesty_park_attempts: int = 0
    """How many times the HV1 honesty gate has withheld this row's
    composed reply because the **model** re-claimed an outcome it had no
    evidence for (F1).

    Only that class of park counts. A park caused by our own judge being
    unreachable says nothing about the row and must never be allowed to
    spend its budget — losing the judge would otherwise cancel every
    outstanding promise on the deployment.

    Bounded because the alternative is unbounded: a park releases the row
    back to ``queued`` with nothing else changed, so a row the model lies
    about systematically would re-compose on every tick forever. At the
    cap the row goes ``cancelled`` with ``last_error`` saying so, loudly
    (ERROR log + an alert-line counter) — never silently."""

    @classmethod
    def new(
        cls,
        *,
        character_id: str,
        conversation_id: str,
        first_message: PendingFollowUpMessage,
        brief_reply: str,
        defer_reason: str,
        scheduled_for: datetime,
        activity_id: str | None = None,
        now: datetime | None = None,
        commitment_key: object = None,
    ) -> "PendingFollowUp":
        timestamp = now or _utcnow()
        reply = (brief_reply or "").strip()
        if not reply:
            raise ValueError("PendingFollowUp brief_reply must be non-empty")
        reason = (defer_reason or "").strip()
        if scheduled_for.tzinfo is None:
            raise ValueError("PendingFollowUp scheduled_for must be tz-aware")
        return cls(
            id=str(uuid4()),
            character_id=character_id,
            conversation_id=conversation_id,
            status=PendingFollowUpStatus.QUEUED,
            messages=(first_message,),
            brief_reply=reply,
            defer_reason=reason,
            activity_id=activity_id,
            scheduled_for=scheduled_for,
            queued_at=timestamp,
            updated_at=timestamp,
            commitment_key=commitment_key,
        )

    @classmethod
    def new_promise(
        cls,
        *,
        character_id: str,
        conversation_id: str,
        promise_intent: str,
        scheduled_for: datetime,
        source_message_content: str = "",
        source_content_mode: MessageContentMode | str = MessageContentMode.NORMAL,
        source_safe_summary: str = "",
        turn_record_id: str | None = None,
        defer_reason: str = SCHEDULED_PROMISE_DEFER_REASON,
        now: datetime | None = None,
        commitment_key: object = None,
    ) -> "PendingFollowUp":
        """Create a ``SCHEDULED_PROMISE`` row.

        Differs from :meth:`new` (which builds a busy-defer row) in:
        - no inline brief_reply is given to the user — the promise was
          spoken in conversation, not a deferred ack
        - ``messages`` carries the original promise request for audit
          (the user's "叫我 10 點起床" turn) so the eventual composer
          can echo specifics back to the user
        - ``promise_intent`` carries the character's interpretation of
          what to do at the scheduled time
        - ``turn_record_id`` names the turn whose post-turn extracted the
          promise, so undoing *that* turn (and only that turn) takes the
          row back with it

        ``turn_record_id`` defaults to ``None`` rather than being
        required because the entity has no way to invent one, but the
        production write point always passes it: without an anchor the
        row falls back to being identified by a time window that its own
        background writer races.

        ``defer_reason`` is the row's *provenance* discriminator, not a
        busy reason — a promise row has no busy activity behind it. It
        exists so the one writer that has to find its own earlier rows
        (the HV4 chat audit, F5) can do so by a stamped mark rather than
        by reading the prose it wrote; see
        :data:`HONESTY_REPAIR_DEFER_REASON`.
        """
        timestamp = now or _utcnow()
        intent = (promise_intent or "").strip()
        if not intent:
            raise ValueError("scheduled-promise row needs promise_intent")
        if scheduled_for.tzinfo is None:
            raise ValueError("PendingFollowUp scheduled_for must be tz-aware")
        # Source message is optional; entity invariant requires at least
        # one queued message, so we synthesise a placeholder when the
        # caller doesn't have the user-turn text handy.
        body = (source_message_content or "").strip() or intent
        source_turn_key = scheduled_promise_source_turn_key(
            source_text=body,
        )
        obligation = ScheduledPromiseObligation(
            intent=intent,
            source_turn_key=source_turn_key,
            source_text=body,
        )
        first = PendingFollowUpMessage.new(
            content=body[:500],
            queued_at=timestamp,
            content_mode=source_content_mode,
            safe_summary=source_safe_summary,
        )
        return cls(
            id=str(uuid4()),
            character_id=character_id,
            conversation_id=conversation_id,
            status=PendingFollowUpStatus.QUEUED,
            messages=(first,),
            brief_reply="(scheduled-promise; no inline ack)",
            defer_reason=(
                (defer_reason or "").strip() or SCHEDULED_PROMISE_DEFER_REASON
            ),
            activity_id=None,
            scheduled_for=scheduled_for,
            queued_at=timestamp,
            updated_at=timestamp,
            kind=PendingFollowUpKind.SCHEDULED_PROMISE,
            promise_intent=intent[:500],
            dedupe_key=scheduled_promise_dedupe_key(
                character_id=character_id,
                promise_intent=intent[:500],
                scheduled_for=scheduled_for,
            ),
            delivery_slot_key=scheduled_promise_delivery_slot_key(
                character_id=character_id,
                scheduled_for=scheduled_for,
            ),
            source_turn_key=source_turn_key,
            obligations=(obligation,),
            turn_record_id=turn_record_id,
            commitment_key=commitment_key,
        )

    @property
    def is_at_cap(self) -> bool:
        return len(self.messages) >= MAX_QUEUED_MESSAGES

    @property
    def is_scheduled_promise(self) -> bool:
        return self.kind == PendingFollowUpKind.SCHEDULED_PROMISE

    @property
    def scheduled_promise_obligations(self) -> tuple[ScheduledPromiseObligation, ...]:
        if self.obligations:
            return self.obligations
        if not self.is_scheduled_promise or not self.promise_intent.strip():
            return ()
        source_text = self.messages[0].content if self.messages else ""
        source_key = self.source_turn_key or scheduled_promise_source_turn_key(
            source_text=source_text or self.promise_intent,
        )
        return (ScheduledPromiseObligation(
            intent=self.promise_intent,
            source_turn_key=source_key,
            source_text=source_text,
        ),)

    @property
    def is_honesty_repair(self) -> bool:
        """Whether the HV4 chat audit minted this row for itself (F5).

        Two equality checks over stamped fields — no reading of
        ``promise_intent``. See :data:`HONESTY_REPAIR_DEFER_REASON` for
        why the mark rides ``defer_reason`` rather than a ``kind`` of its
        own or a column of its own.
        """
        return (
            self.kind == PendingFollowUpKind.SCHEDULED_PROMISE
            and self.defer_reason == HONESTY_REPAIR_DEFER_REASON
        )

    @property
    def latest_user_message(self) -> PendingFollowUpMessage:
        # New rows always have at least one message (entity invariant),
        # so messages[-1] is safe.
        return self.messages[-1]

    def appended(
        self,
        message: PendingFollowUpMessage,
        *,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        """Return a copy with ``message`` appended to the queue.

        The caller (service layer) decides whether to enforce the cap;
        the entity itself always accepts the append so we never silently
        lose user input. ``updated_at`` ticks forward so dispatcher can
        sort by activity.
        """
        from dataclasses import replace

        return replace(
            self,
            messages=self.messages + (message,),
            updated_at=now or _utcnow(),
        )

    def merged_scheduled_promise_context(
        self,
        duplicate: "PendingFollowUp",
    ) -> "PendingFollowUp":
        """Keep one promise row while retaining distinct source context.

        Every promise inside the same 15-minute delivery window is preserved as
        an obligation, but the player receives one natural callback.  A retry
        for the same source/action does not add another obligation.  Exact
        duplicate messages are ignored and the existing queue cap remains in
        force.
        """
        if (
            self.kind != PendingFollowUpKind.SCHEDULED_PROMISE
            or duplicate.kind != PendingFollowUpKind.SCHEDULED_PROMISE
            or not self.delivery_slot_key
            or self.delivery_slot_key != duplicate.delivery_slot_key
        ):
            return self
        merged = list(self.messages)
        seen = {
            (message.content, message.content_mode.value, message.safe_summary)
            for message in merged
        }
        for message in duplicate.messages:
            identity = (
                message.content,
                message.content_mode.value,
                message.safe_summary,
            )
            if identity in seen or len(merged) >= MAX_QUEUED_MESSAGES:
                continue
            merged.append(message)
            seen.add(identity)
        obligations = list(self.scheduled_promise_obligations)
        seen_obligations = {obligation.identity for obligation in obligations}
        for obligation in duplicate.scheduled_promise_obligations:
            if obligation.identity in seen_obligations:
                continue
            obligations.append(obligation)
            seen_obligations.add(obligation.identity)
        if (
            len(merged) == len(self.messages)
            and tuple(obligations) == self.scheduled_promise_obligations
            and duplicate.scheduled_for >= self.scheduled_for
        ):
            return self
        return replace(
            self,
            messages=tuple(merged),
            scheduled_for=min(self.scheduled_for, duplicate.scheduled_for),
            promise_intent=_render_scheduled_promise_intent(obligations),
            obligations=tuple(obligations),
            updated_at=max(self.updated_at, duplicate.updated_at),
        )

    def marked_resolving(self, *, now: datetime | None = None) -> "PendingFollowUp":
        from dataclasses import replace

        return replace(
            self,
            status=PendingFollowUpStatus.RESOLVING,
            updated_at=now or _utcnow(),
        )

    def marked_resolved(
        self,
        *,
        message_text: str,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        from dataclasses import replace

        timestamp = now or _utcnow()
        return replace(
            self,
            status=PendingFollowUpStatus.RESOLVED,
            resolved_message=(message_text or "").strip() or None,
            resolved_at=timestamp,
            updated_at=timestamp,
            last_error=None,
        )

    def marked_failed(
        self,
        *,
        error: str,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        """Flip back to ``QUEUED`` so the next tick can retry, recording
        a short error string for telemetry."""
        from dataclasses import replace

        timestamp = now or _utcnow()
        return replace(
            self,
            status=PendingFollowUpStatus.QUEUED,
            last_error=(error or "").strip()[:200] or None,
            updated_at=timestamp,
        )

    def honesty_parked(
        self,
        *,
        error: str,
        retry_at: datetime,
        attempts: int | None = None,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        """Back to ``QUEUED``, but **not before** ``retry_at`` (F1).

        The difference from :meth:`marked_failed` is the whole point of
        this transition existing: a plain failure leaves ``scheduled_for``
        in the past, which means the very next tick re-reads the row, and
        ``list_due`` — ordered by ``scheduled_for``, limited — hands back
        the same oldest rows every time. A row the honesty gate keeps
        withholding therefore both re-burns a compose per tick and sits at
        the head of the queue starving newer promises. Moving the release
        instant forward is the same lever the row already uses to mean
        "not yet" and fixes both.

        ``attempts`` is passed only by the caller that decided this park
        was the model's fault; leaving it ``None`` keeps the counter
        exactly where it was, which is what a judge outage must do.
        """
        from dataclasses import replace

        timestamp = now or _utcnow()
        if retry_at.tzinfo is None:
            raise ValueError("PendingFollowUp retry_at must be tz-aware")
        return replace(
            self,
            status=PendingFollowUpStatus.QUEUED,
            scheduled_for=retry_at,
            last_error=(error or "").strip()[:200] or None,
            honesty_park_attempts=(
                self.honesty_park_attempts if attempts is None
                else max(0, attempts)
            ),
            updated_at=timestamp,
        )

    def honesty_retries_exhausted(
        self,
        *,
        error: str,
        attempts: int,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        """Terminal: the model re-claimed on every allowed retry (F1).

        Deliberately ``CANCELLED`` rather than another queued retry.
        Every honest option was already spent — the gate blocked, a
        correction naming the exact overclaim was given, and it re-offended
        anyway, ``attempts`` times over. Keeping the row alive past that
        buys no fulfilment and costs a compose per tick forever; keeping
        the row *silently* alive is worse still, which is why this records
        ``error`` and the caller raises an alert line rather than letting
        the row simply stop appearing.
        """
        from dataclasses import replace

        timestamp = now or _utcnow()
        return replace(
            self,
            status=PendingFollowUpStatus.CANCELLED,
            last_error=(error or "").strip()[:200] or None,
            honesty_park_attempts=max(0, attempts),
            updated_at=timestamp,
        )

    def cancelled(self, *, now: datetime | None = None) -> "PendingFollowUp":
        from dataclasses import replace

        timestamp = now or _utcnow()
        return replace(
            self,
            status=PendingFollowUpStatus.CANCELLED,
            updated_at=timestamp,
        )


def _render_scheduled_promise_intent(
    obligations: list[ScheduledPromiseObligation],
) -> str:
    """Keep the legacy scalar intent useful for logs and old callers."""
    combined = "；".join(obligation.intent for obligation in obligations)
    return combined[:500]


@dataclass(frozen=True, slots=True)
class ScheduledPromiseDuplicateGroup:
    """Read-only group of open promises sharing one delivery window.

    The first row is the deterministic canonical candidate (oldest queued
    timestamp, then id).  This is a reporting value only: callers must not
    infer that the remaining rows have been deleted, cancelled, or merged.
    """

    dedupe_key: str
    character_id: str
    promise_intent: str
    scheduled_for: datetime
    rows: tuple[PendingFollowUp, ...]

    @property
    def canonical(self) -> PendingFollowUp:
        return self.rows[0]


def group_open_scheduled_promise_duplicates(
    rows: list[PendingFollowUp] | tuple[PendingFollowUp, ...],
) -> tuple[ScheduledPromiseDuplicateGroup, ...]:
    """Group same-window open scheduled promises without mutating storage.

    Fresh rows already carry ``delivery_slot_key`` and cannot duplicate because
    of the partial unique index.  Legacy rows intentionally have an empty key,
    so this computes the same delivery-window identity before grouping them for
    an operator's review.
    """
    grouped: dict[str, list[PendingFollowUp]] = {}
    for row in rows:
        if (
            row.kind != PendingFollowUpKind.SCHEDULED_PROMISE
            or row.status.value not in {
                PendingFollowUpStatus.QUEUED.value,
                PendingFollowUpStatus.RESOLVING.value,
            }
            or not row.promise_intent.strip()
        ):
            continue
        key = row.delivery_slot_key or scheduled_promise_delivery_slot_key(
            character_id=row.character_id,
            scheduled_for=row.scheduled_for,
        )
        grouped.setdefault(key, []).append(row)

    reports: list[ScheduledPromiseDuplicateGroup] = []
    for key, candidates in grouped.items():
        if len(candidates) < 2:
            continue
        ordered = tuple(sorted(candidates, key=lambda row: (row.queued_at, row.id)))
        canonical = ordered[0]
        reports.append(ScheduledPromiseDuplicateGroup(
            dedupe_key=key,
            character_id=canonical.character_id,
            promise_intent=canonical.promise_intent,
            scheduled_for=canonical.scheduled_for,
            rows=ordered,
        ))
    return tuple(sorted(
        reports,
        key=lambda group: (group.scheduled_for, group.character_id, group.dedupe_key),
    ))
