"""PendingFollowUp — deferred-reply record.

When the character is too busy (high ``busy_score`` activity in progress)
to write a full reply, ``ChatService`` takes a two-step path:

1. Inline turn: a short, in-character "I'm busy — I'll get back to you"
   acknowledgement is generated by the LLM and persisted as the
   assistant message of this turn so the user gets immediate feedback.
2. Pending follow-up: this entity records the user message(s) that
   still need a proper answer. The proactive scheduler later notices the
   character is no longer busy and asks the LLM to write the actual
   reply, which is then fanned out via the existing proactive-message
   pipeline (web SSE + Telegram/LINE bindings).

Concurrency policy — **single defer, then reply**:
  If the user keeps typing while a follow-up is pending, every new
  user message is appended to the row for audit, then ChatService
  cancels the row and lets the normal chat path answer immediately.
  This prevents the worst IM experience: a brief "I'll reply later"
  followed by silent swallowed messages. ``MAX_QUEUED_MESSAGES`` remains
  for legacy rows and dispatcher force-release protection.

Lifecycle:
  ``queued`` → (tick sees busy_score drop) → ``resolving`` → success
  → ``resolved`` (terminal). Failure during resolve flips back to
  ``queued`` so the next tick retries.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from datetime import datetime, timezone
from hashlib import sha256
from typing import ClassVar
from unicodedata import normalize
from uuid import uuid4

from kokoro_link.domain.entities.conversation import MessageContentMode


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


MAX_QUEUED_MESSAGES: int = 8
"""How many user messages can be merged into a single pending row before
the dispatcher force-releases it on the next tick regardless of the
character's current ``busy_score``. Picked so the eventual follow-up
prompt fits comfortably within a single LLM call."""


def scheduled_promise_dedupe_key(
    *,
    character_id: str,
    promise_intent: str,
    scheduled_for: datetime,
) -> str:
    """Return the stable identity for one open scheduled promise.

    Promise extraction can be retried by the post-turn worker, so the random
    row UUID is unsuitable for deduplication.  The promise is instead keyed by
    its character, normalized action, and UTC minute.  Source conversation is
    deliberately excluded: a player should not receive the same promised
    action twice merely because the extractor saw mirrored conversation data.
    """
    if scheduled_for.tzinfo is None:
        raise ValueError("scheduled_for must be tz-aware")
    normalized_intent = " ".join(
        normalize("NFKC", promise_intent).casefold().split(),
    )
    scheduled_minute = scheduled_for.astimezone(timezone.utc).replace(
        second=0, microsecond=0,
    )
    payload = "\x1f".join((
        character_id.strip(),
        PendingFollowUpKind.SCHEDULED_PROMISE.value,
        normalized_intent,
        scheduled_minute.isoformat(),
    ))
    return sha256(payload.encode("utf-8")).hexdigest()


@dataclass(frozen=True, slots=True)
class PendingFollowUpMessage:
    """One queued user message waiting for the deferred reply."""

    content: str
    queued_at: datetime
    content_mode: MessageContentMode = MessageContentMode.NORMAL
    safe_summary: str = ""
    message_id: str | None = None
    """Id of the corresponding ``MessageRow`` (web conversation), when
    available. Optional because TG/LINE inbound messages may not have a
    stable id yet at queue time."""

    @classmethod
    def new(
        cls,
        *,
        content: str,
        queued_at: datetime | None = None,
        content_mode: MessageContentMode | str = MessageContentMode.NORMAL,
        safe_summary: str = "",
        message_id: str | None = None,
    ) -> "PendingFollowUpMessage":
        text = content.strip()
        if not text:
            raise ValueError("PendingFollowUpMessage content must be non-empty")
        return cls(
            content=text,
            queued_at=queued_at or _utcnow(),
            content_mode=_coerce_content_mode(content_mode),
            safe_summary=(safe_summary or "").strip(),
            message_id=message_id,
        )


def _coerce_content_mode(value: MessageContentMode | str) -> MessageContentMode:
    if isinstance(value, MessageContentMode):
        return value
    try:
        return MessageContentMode(str(value).strip().lower())
    except ValueError:
        return MessageContentMode.NORMAL


@dataclass(frozen=True, slots=True)
class PendingFollowUpStatus:
    """String-valued VO so new statuses can be added without alembic."""

    value: str

    QUEUED: ClassVar["PendingFollowUpStatus"]
    RESOLVING: ClassVar["PendingFollowUpStatus"]
    RESOLVED: ClassVar["PendingFollowUpStatus"]
    CANCELLED: ClassVar["PendingFollowUpStatus"]

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("PendingFollowUpStatus value must be non-empty")
        object.__setattr__(self, "value", self.value.strip().lower())

    def __str__(self) -> str:
        return self.value


PendingFollowUpStatus.QUEUED = PendingFollowUpStatus("queued")
PendingFollowUpStatus.RESOLVING = PendingFollowUpStatus("resolving")
PendingFollowUpStatus.RESOLVED = PendingFollowUpStatus("resolved")
PendingFollowUpStatus.CANCELLED = PendingFollowUpStatus("cancelled")


@dataclass(frozen=True, slots=True)
class PendingFollowUpKind:
    """Discriminator for the two reasons a pending follow-up exists.

    * ``BUSY_DEFER`` — the original use case. The user wrote during a
      high-busy activity; the character gave a brief ack inline; the
      full reply is owed when the character is free.
    * ``SCHEDULED_PROMISE`` — the user explicitly asked the character
      to message them at a future time ("明天 10 點叫我起床"). No
      brief ack was given; the message is generated fresh at the
      promised time.

    Kept as a VO (not Enum) so adding new kinds (e.g. ``REMINDER``)
    doesn't require an alembic migration on the column type.
    """

    value: str

    BUSY_DEFER: ClassVar["PendingFollowUpKind"]
    SCHEDULED_PROMISE: ClassVar["PendingFollowUpKind"]

    def __post_init__(self) -> None:
        if not self.value or not self.value.strip():
            raise ValueError("PendingFollowUpKind value must be non-empty")
        object.__setattr__(self, "value", self.value.strip().lower())

    def __str__(self) -> str:
        return self.value


PendingFollowUpKind.BUSY_DEFER = PendingFollowUpKind("busy_defer")
PendingFollowUpKind.SCHEDULED_PROMISE = PendingFollowUpKind("scheduled_promise")


@dataclass(frozen=True, slots=True)
class PendingFollowUp:
    """A promise to the user that an actual reply is coming once the
    character finishes what they're busy with.

    Attribute reference:

    * ``brief_reply`` — the in-character short acknowledgement the user
      already saw inline ("先回會議結束我再好好回你"). The deferred-
      reply LLM call sees this so the eventual full reply can honour
      the promise instead of contradicting it.
    * ``defer_reason`` — short label from the busy-decider ("會議中" /
      "通勤" / "深度工作") for telemetry + prompt context. Not
      enumerated; whatever the LLM wrote stays.
    * ``scheduled_for`` — earliest time the dispatcher should consider
      releasing this row. The dispatcher additionally checks the
      character's current busy_score; both gates must pass.
    * ``messages`` — tuple of queued user messages (FIFO order). New
      messages append via :meth:`appended`. Cap enforced at the service
      layer, not the entity, so the dispatcher can choose to force-
      release at-cap rather than rejecting the append (UX: never silently
      drop the user's words).
    """

    id: str
    character_id: str
    conversation_id: str
    status: PendingFollowUpStatus
    messages: tuple[PendingFollowUpMessage, ...]
    brief_reply: str
    defer_reason: str
    activity_id: str | None
    """``ScheduleActivity.id`` the decider was looking at when it
    deferred. Optional because the user might message during a schedule
    gap where ``busy_score`` is high for a non-schedule reason (e.g.
    energy heuristic). Used for telemetry / debugging only — the
    dispatcher re-resolves the current activity at release time."""
    scheduled_for: datetime
    queued_at: datetime
    updated_at: datetime
    resolved_at: datetime | None = None
    resolved_message: str | None = None
    """The full deferred-reply text once successfully delivered. Kept
    for audit / debugging — the eventual outbound is also written into
    the conversation history through the normal fan-out path."""
    last_error: str | None = None
    kind: PendingFollowUpKind = field(
        default_factory=lambda: PendingFollowUpKind.BUSY_DEFER,
    )
    """Why this row exists. ``BUSY_DEFER`` (default) keeps every legacy
    code path identical; ``SCHEDULED_PROMISE`` routes the dispatcher to
    the scheduled-promise composer and skips the busy-score release
    gate (the original promise didn't promise "when I'm free", it
    promised "at this specific time")."""
    promise_intent: str = ""
    """The natural-language description of what the character promised
    to do at the scheduled time (例:「叫使用者起床」「提醒喝水」).
    Only meaningful when ``kind == SCHEDULED_PROMISE``; ignored for
    ``BUSY_DEFER``. The composer reads this to write the actual message
    — the persona + intent + current context drive content, no
    templating."""
    dedupe_key: str = ""
    """Stable key for an open scheduled promise.

    Legacy rows intentionally keep this blank.  Only the database's partial
    unique index treats a non-empty key as a deduplication constraint, allowing
    a later promise after a row has reached a terminal status.
    """

    @classmethod
    def new(
        cls,
        *,
        character_id: str,
        conversation_id: str,
        first_message: PendingFollowUpMessage,
        brief_reply: str,
        defer_reason: str,
        scheduled_for: datetime,
        activity_id: str | None = None,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        timestamp = now or _utcnow()
        reply = (brief_reply or "").strip()
        if not reply:
            raise ValueError("PendingFollowUp brief_reply must be non-empty")
        reason = (defer_reason or "").strip()
        if scheduled_for.tzinfo is None:
            raise ValueError("PendingFollowUp scheduled_for must be tz-aware")
        return cls(
            id=str(uuid4()),
            character_id=character_id,
            conversation_id=conversation_id,
            status=PendingFollowUpStatus.QUEUED,
            messages=(first_message,),
            brief_reply=reply,
            defer_reason=reason,
            activity_id=activity_id,
            scheduled_for=scheduled_for,
            queued_at=timestamp,
            updated_at=timestamp,
        )

    @classmethod
    def new_promise(
        cls,
        *,
        character_id: str,
        conversation_id: str,
        promise_intent: str,
        scheduled_for: datetime,
        source_message_content: str = "",
        source_content_mode: MessageContentMode | str = MessageContentMode.NORMAL,
        source_safe_summary: str = "",
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        """Create a ``SCHEDULED_PROMISE`` row.

        Differs from :meth:`new` (which builds a busy-defer row) in:
        - no inline brief_reply is given to the user — the promise was
          spoken in conversation, not a deferred ack
        - ``messages`` carries the original promise request for audit
          (the user's "叫我 10 點起床" turn) so the eventual composer
          can echo specifics back to the user
        - ``promise_intent`` carries the character's interpretation of
          what to do at the scheduled time
        """
        timestamp = now or _utcnow()
        intent = (promise_intent or "").strip()
        if not intent:
            raise ValueError("scheduled-promise row needs promise_intent")
        if scheduled_for.tzinfo is None:
            raise ValueError("PendingFollowUp scheduled_for must be tz-aware")
        # Source message is optional; entity invariant requires at least
        # one queued message, so we synthesise a placeholder when the
        # caller doesn't have the user-turn text handy.
        body = (source_message_content or "").strip() or intent
        first = PendingFollowUpMessage.new(
            content=body[:500],
            queued_at=timestamp,
            content_mode=source_content_mode,
            safe_summary=source_safe_summary,
        )
        return cls(
            id=str(uuid4()),
            character_id=character_id,
            conversation_id=conversation_id,
            status=PendingFollowUpStatus.QUEUED,
            messages=(first,),
            brief_reply="(scheduled-promise; no inline ack)",
            defer_reason="scheduled_promise",
            activity_id=None,
            scheduled_for=scheduled_for,
            queued_at=timestamp,
            updated_at=timestamp,
            kind=PendingFollowUpKind.SCHEDULED_PROMISE,
            promise_intent=intent[:500],
            dedupe_key=scheduled_promise_dedupe_key(
                character_id=character_id,
                promise_intent=intent[:500],
                scheduled_for=scheduled_for,
            ),
        )

    @property
    def is_at_cap(self) -> bool:
        return len(self.messages) >= MAX_QUEUED_MESSAGES

    @property
    def is_scheduled_promise(self) -> bool:
        return self.kind == PendingFollowUpKind.SCHEDULED_PROMISE

    @property
    def latest_user_message(self) -> PendingFollowUpMessage:
        # New rows always have at least one message (entity invariant),
        # so messages[-1] is safe.
        return self.messages[-1]

    def appended(
        self,
        message: PendingFollowUpMessage,
        *,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        """Return a copy with ``message`` appended to the queue.

        The caller (service layer) decides whether to enforce the cap;
        the entity itself always accepts the append so we never silently
        lose user input. ``updated_at`` ticks forward so dispatcher can
        sort by activity.
        """
        from dataclasses import replace

        return replace(
            self,
            messages=self.messages + (message,),
            updated_at=now or _utcnow(),
        )

    def merged_scheduled_promise_context(
        self,
        duplicate: "PendingFollowUp",
    ) -> "PendingFollowUp":
        """Keep one promise row while retaining distinct source context.

        Repeated extraction can see a mirrored or slightly fuller source turn.
        That source is useful audit/composer context, but it must not create a
        second release target. Exact duplicate messages are ignored and the
        existing queue cap remains in force.
        """
        if (
            self.kind != PendingFollowUpKind.SCHEDULED_PROMISE
            or duplicate.kind != PendingFollowUpKind.SCHEDULED_PROMISE
            or not self.dedupe_key
            or self.dedupe_key != duplicate.dedupe_key
        ):
            return self
        merged = list(self.messages)
        seen = {
            (message.content, message.content_mode.value, message.safe_summary)
            for message in merged
        }
        for message in duplicate.messages:
            identity = (
                message.content,
                message.content_mode.value,
                message.safe_summary,
            )
            if identity in seen or len(merged) >= MAX_QUEUED_MESSAGES:
                continue
            merged.append(message)
            seen.add(identity)
        if len(merged) == len(self.messages):
            return self
        return replace(
            self,
            messages=tuple(merged),
            updated_at=max(self.updated_at, duplicate.updated_at),
        )

    def marked_resolving(self, *, now: datetime | None = None) -> "PendingFollowUp":
        from dataclasses import replace

        return replace(
            self,
            status=PendingFollowUpStatus.RESOLVING,
            updated_at=now or _utcnow(),
        )

    def marked_resolved(
        self,
        *,
        message_text: str,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        from dataclasses import replace

        timestamp = now or _utcnow()
        return replace(
            self,
            status=PendingFollowUpStatus.RESOLVED,
            resolved_message=(message_text or "").strip() or None,
            resolved_at=timestamp,
            updated_at=timestamp,
            last_error=None,
        )

    def marked_failed(
        self,
        *,
        error: str,
        now: datetime | None = None,
    ) -> "PendingFollowUp":
        """Flip back to ``QUEUED`` so the next tick can retry, recording
        a short error string for telemetry."""
        from dataclasses import replace

        timestamp = now or _utcnow()
        return replace(
            self,
            status=PendingFollowUpStatus.QUEUED,
            last_error=(error or "").strip()[:200] or None,
            updated_at=timestamp,
        )

    def cancelled(self, *, now: datetime | None = None) -> "PendingFollowUp":
        from dataclasses import replace

        timestamp = now or _utcnow()
        return replace(
            self,
            status=PendingFollowUpStatus.CANCELLED,
            updated_at=timestamp,
        )


@dataclass(frozen=True, slots=True)
class ScheduledPromiseDuplicateGroup:
    """Read-only group of legacy open promises with one logical identity.

    The first row is the deterministic canonical candidate (oldest queued
    timestamp, then id).  This is a reporting value only: callers must not
    infer that the remaining rows have been deleted, cancelled, or merged.
    """

    dedupe_key: str
    character_id: str
    promise_intent: str
    scheduled_for: datetime
    rows: tuple[PendingFollowUp, ...]

    @property
    def canonical(self) -> PendingFollowUp:
        return self.rows[0]


def group_open_scheduled_promise_duplicates(
    rows: list[PendingFollowUp] | tuple[PendingFollowUp, ...],
) -> tuple[ScheduledPromiseDuplicateGroup, ...]:
    """Group duplicate open scheduled promises without mutating storage.

    Fresh rows already carry ``dedupe_key`` and cannot duplicate because of the
    partial unique index.  Legacy rows intentionally have an empty stored key,
    so this computes the same deterministic identity from their content before
    grouping them for an operator's review.
    """
    grouped: dict[str, list[PendingFollowUp]] = {}
    for row in rows:
        if (
            row.kind != PendingFollowUpKind.SCHEDULED_PROMISE
            or row.status.value not in {
                PendingFollowUpStatus.QUEUED.value,
                PendingFollowUpStatus.RESOLVING.value,
            }
            or not row.promise_intent.strip()
        ):
            continue
        key = scheduled_promise_dedupe_key(
            character_id=row.character_id,
            promise_intent=row.promise_intent,
            scheduled_for=row.scheduled_for,
        )
        grouped.setdefault(key, []).append(row)

    reports: list[ScheduledPromiseDuplicateGroup] = []
    for key, candidates in grouped.items():
        if len(candidates) < 2:
            continue
        ordered = tuple(sorted(candidates, key=lambda row: (row.queued_at, row.id)))
        canonical = ordered[0]
        reports.append(ScheduledPromiseDuplicateGroup(
            dedupe_key=key,
            character_id=canonical.character_id,
            promise_intent=canonical.promise_intent,
            scheduled_for=canonical.scheduled_for,
            rows=ordered,
        ))
    return tuple(sorted(
        reports,
        key=lambda group: (group.scheduled_for, group.character_id, group.dedupe_key),
    ))
